### ISSUE TITLE
Feature Request: Add "astroconda-contrib" column

### ISSUE THREAD

**Issue by pllim** [sosey/repo-summary#10]
"astroconda-dev" is not visible to outside world, so while informative for internal developers, not very useful. However, "astroconda-contrib" reflects what is in the "astroconda" channel, so I think adding that column would tell me whether I need to also make a PR to a recipe there when I make a release.

**Comment by sosey** [comment]
dev and contrib are displayed on default, 4d150a2a723fc7dcd801658c2fa186fe369dfd9a
