### ISSUE TITLE
Bug: License column is inaccurate

### ISSUE THREAD

**Issue by pllim** [sosey/repo-summary#13]
Some packages have a clear license file in the repo, but the license column says "None", which is misleading. Examples (non-exhaustive): PyFITS, `synphot_refactor`, `stsynphot_refactor`.

**Comment by sosey** [comment]
I'm pulling the license from the api listing, that may get populated differently than just checking if a file exists...will check

**Comment by pllim** [comment]
Another example is `asdf`. Its license file is under `licenses` sub-directory instead of top-level. FYI.

**Comment by sosey** [comment]
Git detects the license in a specific way, if the repo doesn't conform, the API wont return a result. 
https://help.github.com/articles/adding-a-license-to-a-repository/
I suggest we can use this to  find  such repositories, then someone (not me) can decide if they want to normalize how they are done for all repos...

**Comment by pllim** [comment]
But from this webpage POV, better not show a column than an inaccurate one?

**Comment by sosey** [comment]
I don't necessarily agree, the columns are still providing useful information, and this is mostly for internal reference

**Comment by pllim** [comment]
OK let's agree to disagree then. Maybe add a disclaimer at least (if you don't have one already)?
