### ISSUE TITLE
Feature Request: Display "archived" status

### ISSUE THREAD

**Issue by pllim** [sosey/repo-summary#14]
This was requested by @saraogaz on Confluence. For example, PyFITS is archived.

I think an extra column is unnecessary for this as we don't have that many archived packages (do we?). Maybe an icon in the "package name" column or the like?

Alternately, maybe can separate those out into a second table at the bottom? This way, we don't even need any special icon.

**Comment by SaOgaz** [comment]
we don't have that many archived packages *yet* ;)

**Comment by sosey** [comment]
I didn't see an easy api data member I could grab, feel free to look for one or think of a way to do this for archived repos, I accept pull requests... ;)

I have a scratch function to create separate html pages given a list of repos.... not pushed yet, I was thinking of just making separate pages for astronconda, datb, scsb, etc...

**Comment by SaOgaz** [comment]
Ahh, bummer.  I'll try and look into it if I ever have some free time... *hysterical laughter*.

**Comment by sosey** [comment]
added in 4d150a2a723fc7dcd801658c2fa186fe369dfd9a
