### ISSUE TITLE
Bug: Doc build status inaccurate when RTD name is different from repo name

### ISSUE THREAD

**Issue by pllim** [sosey/repo-summary#15]
For `synphot_refactor`, the RTD is http://synphot.readthedocs.io/en/latest/

For `stsynphot_refactor`, the RTD is http://stsynphot.readthedocs.io/en/latest/

Not sure how you can generalize this fix. Case-by-case exception is fine by me. Sorry for the inconvenience.

**Comment by sosey** [comment]
I think since this is hard to generalize, we could return an explicit string that says see the repository, or just leave it as the docs-unknown icon, either is a heads up to look at the repository itself.

**Comment by pllim** [comment]
No way I can insert some exception rules just for these two?

**Comment by sosey** [comment]
if you're willing to look through all the repositories, note which ones don't point to docs not with the same name of the repo, and lists where they should point instead,  and then submit a PR that deals with this, I'll happily accept.  More generally it should probably be a separate function that pulls the readme file for repo and scrapes for the badge locations to rtd

**Comment by pllim** [comment]
Badge scraping works for me!

**Comment by sosey** [comment]
excellent, I look forward to your PR then ;)

**Comment by pllim** [comment]
Wait... That is not what I meant... :sweat_smile:
