### ISSUE TITLE
Feature request: Track repos being displayed in a user-configurable data file

### ISSUE THREAD

**Issue by pllim** [sosey/repo-summary#16]
~~Currently, it is unclear to me where this list of repositories are kept.~~ (Okay, I just saw the README, my bad, but my request still stands.) Understandably, at this stage, the list might be incomplete. I am sure you have plans to make a complete list. However it would be nice also for people to see such a list here, so they can make PRs to correct it in the future.

**Comment by sosey** [comment]
There is no list, all repos in an organization are grabbed, the page I sent you was merely an *example* of the layout and information for discussion and some bug fixing.

**Comment by pllim** [comment]
Right. But I am saying that it *would be nice* to have a configurable list. There are so many repos in that org that we don't care about.

**Comment by sosey** [comment]
that's why there's a function to just look at a few...

**Comment by sosey** [comment]
You can generate the webpage of repositories from any list of repositories. Getting the data and generating the webpage are separate functions. I'll post examples soon.
