### ISSUE TITLE
Use github3?

### ISSUE THREAD

**Issue by pllim** [sosey/repo-summary#21]
Pro: Simplify GitHub API calls, or at least make them easier to read.
Con: Introduce third-party dependency.

`github3` doc is at https://github3py.readthedocs.io/en/latest/

**Comment by sosey** [comment]
I would really rather not use github3

**Comment by pllim** [comment]
Why? License?

**Comment by sosey** [comment]
there's no clear license, it's not being maintained, and github is getting ready to switch to GraphQL

**Comment by pllim** [comment]
OK
