### ISSUE TITLE
DOC: Authentication gotchas

### ISSUE THREAD

**Issue by pllim** [sosey/repo-summary#22]
When you get prompted for GitHub username and token and entered the wrong one, you need to delete a hidden file to start over. This should be documented.

In addition, maybe some instructions to generate token for new users. (I already have one, so I wasn't hindered by this, but others might.)

**Comment by sosey** [comment]
Its in the documentation, maybe give me a chance to push the docs first before making new issues for a while?

**Comment by sosey** [comment]
should be documented now
