### ISSUE TITLE
Bug: Horizontal scroll bar hidden at the bottom

### ISSUE THREAD

**Issue by pllim** [sosey/repo-summary#4]
I can't see left-right scroll bar until I scroll all the way down. This means if I want to see the entire first row, I need to scroll down, scroll left/right, scroll up, repeat.

Was using Firefox 52.5.1 (64-bit) on RHEL7.

**Comment by sosey** [comment]
hmm, I use my mouse/trackpad to scroll inside the table.... was trying to avoid setting the table length but we could do that

**Comment by pllim** [comment]
My mouse-fu is not that strong (or could be weird RHEL7 config). :sweat_smile: :mouse:

**Comment by sosey** [comment]
I made the size of the whole table static, see if this works better for you
4d150a2a723fc7dcd801658c2fa186fe369dfd9a

**Comment by pllim** [comment]
Yes, I can see both scroll bars now. Thanks!
