### ISSUE TITLE
Feature request: Make first column "sticky"

### ISSUE THREAD

**Issue by pllim** [sosey/repo-summary#5]
Would be nice to have "Package Name" to remain in view when I scroll all the way to the right. Otherwise, for example, I have to memorize which package is which row first to figure out which RTD build in failing.

**Comment by sosey** [comment]
"sticky" rows and columns  are rather difficult to get right across all browsers, I played with this last night and couldn't get it to work. we'll see. On Chrome, the header row *is* sticky, what are you using?

**Comment by pllim** [comment]
Firefox 52.5.1 (64-bit) on RHEL7. Do I need a special plugin?

**Comment by sosey** [comment]
fixed in 4d150a2a723fc7dcd801658c2fa186fe369dfd9a

**Comment by pllim** [comment]
Fancy! :+1:
