### ISSUE TITLE
Feature request: Button to export table data to a file

### ISSUE THREAD

**Issue by pllim** [sosey/repo-summary#7]
Preferably a format that can be ingested by `astropy.table.Table`. Maybe ECSV?

**Comment by sosey** [comment]
The data are saved as json when retrieved and can be imported into any python session for manipulation. I think this is the better interaction format. The html page is for quick reference and linking.

**Comment by pllim** [comment]
In that case, perhaps documentation on how to do such things? :smile:

**Comment by sosey** [comment]
should be in the docs
