### ISSUE TITLE
Feature Request: Add a new column called "Open PRs"

### ISSUE THREAD

**Issue by pllim** [sosey/repo-summary#8]
Personally, I would be more interested to know about how many open PRs. How many forked and starred the repo is irrelevant.

**Comment by sosey** [comment]
forked and stars also relate how popular they are in the community and how many people might be working or contributing to them.

**Comment by pllim** [comment]
Fine, then just add a new column called "Open PRs"? :smile:

**Comment by sosey** [comment]
open PR count added  4d150a2a723fc7dcd801658c2fa186fe369dfd9a
