### ISSUE TITLE
Bug: Sorting by package name does not make sense

### ISSUE THREAD

**Issue by pllim** [sosey/repo-summary#9]
Why would "PyFITS" be listed first when I sort by ascending alphabetical order by package name?

**Comment by sosey** [comment]
capitalization

**Comment by pllim** [comment]
But, but... still doesn't make sense to me... :sweat_smile:

**Comment by pllim** [comment]
Maybe de-capitalize before sorting?

**Comment by sosey** [comment]
I don't think that's possible, I didn't write the sorting function, it's going through google viz
